apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: KafkaSender
  name: KafkaSender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KafkaSender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empty-nginx
    spec:
      containers:
         - image: nikdesaedeleir/githubactions:0.1.41.11050945301
          name: KafkaSender
          resources: {}
status: {}