apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafkasender
  name: kafkasender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkasender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empty-nginx
    spec:
      containers:
        - image: nikdesaedeleir/githubactions:0.1.43.11051324273
          name: kafkasender
          imagePullPolicy: Always
status: {}