apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: empty-nginx
  name: empty-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: empty-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: empty-nginx
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources: {}
status: {}