name: Build and Push Docker Image

on:
  push:
    branches:
      - main
env:
  CONTAINER_VERSION: latest
  DOCKER_REPO: githubactions
  SOURCE_DIR: kafkasender
jobs:
  build:
    runs-on: ubuntu-latest
    environment: GitHubActions
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Set up JDK 17  # or the appropriate Java version you're using
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

#      - name: Build with Maven
#        working-directory: ${{env.SOURCE_DIR}}
#        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
      - run: ls
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ../../${{env.SOURCE_DIR}}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.CONTAINER_VERSION}}
